name: AWS
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/winmg1/linux/main/ngrok.zip -OutFile ngrok.zip
        
    - name: Extract ngrok Files
      run: unzip ngrok.zip

    - name: Connecting ngrok Account
      run: ./ngrok config add-authtoken 22KZgjApveZgMuakhioJmKNmgP4_YzCkFcdrWumhCpHC45pZ
        
    - name: Create Tunnel
      run: ./ngrok tcp 3389

    - name: Linux SSh
      run: apt update > /dev/null 2>&1
	apt install openssh-server > /dev/null 2>&1
      
